[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_twitter = "DHNmSyaVqxWCEcFPiZKY2nC8umJqezvnAkSJfR1nrvZL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/main/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
